/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"

float *
suma_1_svc(digitos_op *argp, struct svc_req *rqstp)
{
	static float result;
	float temp_a=argp->a;
	float temp_b=argp->b;
	printf("\nFunción suma (%f + %f)\n",temp_a,temp_b);
	result=temp_a+temp_b;
	printf("\nResultado es %f",result);
	return &result;
}

float *
resta_1_svc(digitos_op *argp, struct svc_req *rqstp)
{
	static float  result;
	float temp_a=argp->a;
	float temp_b=argp->b;
	printf("\nFUnción resta (%f - %f)\n",temp_a,temp_b);
	result=temp_a-temp_b;
	printf("\nResultado es %f",result);
	return &result;
}

float *
multiplicacion_1_svc(digitos_op *argp, struct svc_req *rqstp)
{
	static float  result;
	float temp_a=argp->a;
	float temp_b=argp->b;
	printf("\nFunción multiplicación (%f * %f)\n",temp_a,temp_b);
	result=temp_a*temp_b;
	printf("\nResultado es %f",result);
	return &result;
}

float *
division_1_svc(digitos_op *argp, struct svc_req *rqstp)
{
	static float  result;
	float temp_a=argp->a;
	float temp_b=argp->b;
	printf("\nFunción división (%f / %f)\n",temp_a,temp_b);
	result=temp_a/temp_b;
	printf("\nResultado es %f",result);
	return &result;
}
