/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"


void
calc_prog_1(char *host,int op,float a,float b)
{
	CLIENT *clnt;
	float  *result_1;
	digitos_op  suma_1_arg;
	float  *result_2;
	digitos_op  resta_1_arg;
	float  *result_3;
	digitos_op  multiplicacion_1_arg;
	float  *result_4;
	digitos_op  division_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, CALC_PROG, CALC_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	switch(op) {
		case 1:
		suma_1_arg.a=a;suma_1_arg.b=b;
		result_1 = suma_1(&suma_1_arg, clnt);
		if (result_1 == (float *) NULL) {
			clnt_perror (clnt, "call failed");
			}
		printf("\nResultado: %f\n",*result_1);
		break;
		case 2:
		resta_1_arg.a=a;resta_1_arg.b=b;
		result_2 = resta_1(&resta_1_arg, clnt);
		if (result_2 == (float *) NULL) {
			clnt_perror (clnt, "call failed");
			}
		printf("\nResultado: %f\n",*result_2);
		break;
		case 3:
		multiplicacion_1_arg.a=a;multiplicacion_1_arg.b=b;
		result_3 = multiplicacion_1(&multiplicacion_1_arg, clnt);
		if (result_3 == (float *) NULL) {
			clnt_perror (clnt, "call failed");
			}
		printf("\nResultado: %f\n",*result_3);
		break;
		case 4:
		division_1_arg.a=a;division_1_arg.b=b;
		result_4 = division_1(&division_1_arg, clnt);
		if (result_4 == (float *) NULL) {
			clnt_perror (clnt, "call failed");
			}
		printf("\nResultado: %f\n",*result_4);
		break;	
		default:
		break;
	}

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	int op;
	float a,b;
	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	while(op!=5){
	printf("\nSleccione una opción\n");
	printf("\n1. Suma\n2. Resta\n3. Multiplicación\n4. Division\n5. Salir\n");
		scanf("%d",&op);
	if(op==1 || op==2 || op==3 || op==4) {
		printf("\nIngrese el primer numero: ");
		scanf("%f",&a);
		printf("\nIngrese el segundo numero: ");
		scanf("%f",&b);
		calc_prog_1 (host,op,a,b);
		
		}else {
				printf("\n   Opción no valida. Vuelve a intentar.\n\n");
				
			}}
			exit (0);
}
